[package]
name = "tikal"
version = "0.1.0"
edition = "2024"

[lib]
name = "tikal"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = { version = "0.27.2", features = [
    "extension-module",
    "experimental-async",
] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "mysql",
    "postgres",
    "sqlite",
    "chrono",
    "json",
] }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
once_cell = "1.19"

[[test]]
name = "run_all"
path = "test/run_all.rs"

# cargo test --test run_all
