[package]
name = "test_users"
version = "0.1.0"
edition = "2024"

[dependencies]
tikal = { path = "../../" }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
